name: learn-github-actions

run-name: ${{ github.actor }} is learning GitHub Actions

on: 
  # Triggers the workflow on push request events but only for the main branch 
  #push:
  #  branches: [ main ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# ref: https://docs.github.com/zh/actions/using-workflows/about-workflows
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

      - name: Hello World
        run: echo "Hello, World!"

      - name: Print System Info
        run: |
          echo "Operating System:"
          uname -a
          echo "CPU Info:"
          lscpu
          echo "Memory Info:"
          free -h