name: Build and Publish

run-name: ${{ github.actor }} is learning GitHub Actions to build and publish

on: 
  # Triggers the workflow on push request events but only for the main branch 
  push:
    branches: [ main ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  release:
    types:
      - created

jobs:

  build_image:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build CentOS Image
        run: |
          # 使用 CentOS 8 作为基础镜像
          # 复制 Hello World Python 脚本到容器中
          # 指定容器启动时执行的命令
          echo 'FROM centos:8
          COPY hello.py /root/
          CMD ["python", "/root/hello.py"]' > Dockerfile

          # 构建镜像
          docker build -t my-centos-image .

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag and Push Docker Image
        run: |
          docker tag my-centos-image:latest ghcr.io/${{ github.repository }}/my-centos-image:latest
          docker push ghcr.io/${{ github.repository }}/my-centos-image:latest

  release:
    needs: build_image
    runs-on: ubuntu-latest

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0  # 替换为您希望的发布标签
          release_name: Release v1.0  # 替换为您希望的发布名称
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Docker Image to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./path/to/your/image.tar.gz  # 替换为您的 Docker 镜像文件路径
          asset_name: my-centos-image.tar.gz  # 替换为您的 Docker 镜像文件名
          asset_content_type: application/x-gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}